version: "3"
services:
  app:
    build: .
    ports:
      - "5001:5001"
    container_name: flask_app
    environment:
      FLASK_APP: "app/app.py"
      FLASK_ENV: "development"
    command: "flask run --host=0.0.0.0 --port=5001"